// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utocodicppxdaxjuomzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0b2NvZGljcHB4ZGF4anVvbXpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTY5ODMsImV4cCI6MjA2MTg3Mjk4M30.uRKNBet9eP5gWIdAK6indtgwSLHIF-cQnnkRhBHUFeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);